### ISSUE TITLE
Support Multi-components from a single github repository

### ISSUE THREAD

**Issue by apupier** [openshift/odo#1014]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

I guess most of the commands are affected

## Why is this needed? 

Most used Fuse booster is designed this way https://github.com/jboss-fuse/fuse-springboot-circuit-breaker-booster and it seems a regular way of packaging several components with tight lifecycle.

currently I have this kind of error

```
"C:\Users\Aurelien Pupier\.vs-openshift\odo.exe" push --local c:\ws\workingDirectoryForTest\test-circuitBreaker-withFixedSpringbootdashboard\fuse-springboot-circuit-breaker-booster\name-service
Pushing changes to component: name-service
Please wait, building component....
+ set -eo pipefail
+ '[' -f /opt/app-root/src/.s2i/bin/assemble ']'
+ '[' -f /usr/local/s2i/assemble ']'
+ rm -rf /opt/app-root/src/.git
+ cp -a /opt/app-root/src/. /tmp/src
+ /usr/local/s2i/assemble
==================================================================
Starting S2I Java Build .....
Maven build detected
Initialising default settings /tmp/artifacts/configuration/settings.xml
Setting MAVEN_OPTS to -XX:+UseParallelOldGC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError
Found pom.xml ... 
Running 'mvn -Dmaven.repo.local=/tmp/artifacts/m2 -s /tmp/artifacts/configuration/settings.xml -e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga -Dfabric8.skip=true package --batch-mode -Djava.net.preferIPv4Stack=true '
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
�[1mApache Maven 3.5.0 (Red Hat 3.5.0-4.3)�[m
Maven home: /opt/rh/rh-maven35/root/usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-862.11.6.el7.x86_64", arch: "amd64", family: "unix"
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Downloading: https://repo1.maven.org/maven2/com/redhat/fuse/boosters/fuse-springboot-circuit-breaker-booster-parent/7.0.0.redhat-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://repo1.maven.org/maven2/com/redhat/fuse/boosters/fuse-springboot-circuit-breaker-booster-parent/7.0.0.redhat-SNAPSHOT/fuse-springboot-circuit-breaker-booster-parent-7.0.0.redhat-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.redhat.fuse.boosters:name-service:[unknown-version]: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.redhat.fuse.boosters:name-service:[unknown-version]: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 13

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:382)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project com.redhat.fuse.boosters:name-service:[unknown-version] (/tmp/src/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.redhat.fuse.boosters:name-service:[unknown-version]: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 13 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:197)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:243)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1051)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:429)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:398)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:362)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:303)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:193)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:258)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:529)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
	... 29 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Aborting due to error code 1 for Maven build
failed to push component: name-service
```

**Comment by apupier** [comment]
if trying to call on parent folder:
```
[INFO] Fuse :: Boosters :: Springboot :: Circuit Breaker .. SUCCESS [  0.005 s]
[INFO] Fuse :: Boosters :: Springboot :: Circuit Braker :: Name service SUCCESS [01:51 min]
[INFO] Fuse :: Boosters :: Springboot :: Circuit Braker :: Greetings service SUCCESS [  3.877 s]
[INFO] Fuse :: Boosters :: Springboot :: Circuit Braker :: Integration Tests SUCCESS [ 21.465 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:56 min
[INFO] Finished at: 2018-11-20T13:19:04Z
[INFO] Final Memory: 61M/97M
[INFO] ------------------------------------------------------------------------
Copying Maven artifacts from /tmp/src/target to /deployments ...
Running: cp *.jar /deployments
/usr/local/s2i/assemble: line 71: cd: /tmp/src/target: No such file or directory
cp: cannot stat '*.jar': No such file or directory
Aborting due to error code 1 for copying artifacts from /tmp/src/target to /deployments
failed to push component: circuit-breaker
```
