### ISSUE TITLE
Support for GB, gb, Gb, Gi, gi, GI, MB, mb, Mb, Mi, MI, mi for memory and fail gracefully

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/odo#1170]
[kind/bug]

## What versions of software are you using?
- Operating System:
mac os X 10.14.2
- Output of `odo version`:
odo v0.0.17 (78a050bc)

## How did you run odo exactly?
```
odo create java backend --binary target/wildwest-1.0.jar --memory 1GB --cpu 1
```

## Actual behavior
```
 ✓  Checking component
 ✓  Checking component version
panic: cannot parse '1GB': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 1 [running]:
github.com/redhat-developer/odo/vendor/k8s.io/apimachinery/pkg/api/resource.MustParse(0x7ffeefbff882, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/redhat-developer/odo/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:133 +0x249
github.com/redhat-developer/odo/pkg/util.FetchResourceQuantity(0x2440628, 0x6, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbff882, 0x3, 0x0)
	/home/travis/gopath/src/github.com/redhat-developer/odo/pkg/util/util.go:329 +0xdb
github.com/redhat-developer/odo/pkg/odo/cli/component.glob..func4(0x36c0380, 0xc0006d5a00, 0x2, 0x8)
	/home/travis/gopath/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:193 +0x817
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).execute(0x36c0380, 0xc0006d5900, 0x8, 0x8, 0x36c0380, 0xc0006d5900)
	/home/travis/gopath/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000702480, 0x8, 0xc000000300, 0x20794c2)
	/home/travis/gopath/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000702480, 0x253fb90, 0xc00010aa80)
	/home/travis/gopath/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/home/travis/gopath/src/github.com/redhat-developer/odo/cmd/odo/odo.go:64 +0x350
```

## Expected behavior
App creation OK, or graceful error stating the supported format for memory argument qualifier.

**Comment by girishramnani** [comment]
@jorgemoralespou could you try `odo create java backend --binary target/wildwest-1.0.jar --memory 1G --cpu 1`?

**Comment by jorgemoralespou** [comment]
> odo create java backend --binary target/wildwest-1.0.jar --memory 1G --cpu 1
That one works.

Maybe clarify what's supported in the help, and just fail gracefully if the format is not supported. Also, do the check of supported valid arguments before any other checks.
````
odo create -h 
...
--memory string       Amount of memory to be allocated to the component. ex. 100Mi
...
```

**Comment by girishramnani** [comment]
This issue is a subset of https://github.com/openshift/odo/issues/1549. 
And hence closing.
