### ISSUE TITLE
Config set port panic out

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#1523]
[kind/bug]

## What versions of software are you using?
- Operating System: 
- Output of `odo version`: master

## How did you run odo exactly?
$ odo config set Ports 8080/TCP  - panic out
$ odo config set ports 8080/TCP - panic out
$ odo config set --ports 8080/TCP - unknown flag: --ports

## Actual behavior
Fails

## Expected behavior
Should set

## Any logs, error output, etc?
```
$ odo config set ports 8080/TCP
panic: interface conversion: interface {} is string, not []string

goroutine 1 [running]:
github.com/openshift/odo/pkg/config.(*LocalConfigInfo).SetConfiguration(0xc00013efd0, 0x7ffeefbffbcf, 0x5, 0x2296560, 0xc000af3410, 0x0, 0x2593d53)
        /Users/amit/go/src/github.com/openshift/odo/pkg/config/config.go:184 +0x103b
github.com/openshift/odo/pkg/odo/cli/config.(*SetOptions).Run(0xc0004ebe00, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/config/set.go:106 +0x105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x28182a0, 0xc0004ebe00, 0xc0007acb40, 0xc0006c0180, 0x2, 0x2)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17 +0xf2
github.com/openshift/odo/pkg/odo/cli/config.NewCmdSet.func2(0xc0007acb40, 0xc0006c0180, 0x2, 0x2)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/config/set.go:142 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0007acb40, 0xc0006c0120, 0x2, 0x2, 0xc0007acb40, 0xc0006c0120)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00059b440, 0x0, 0x0, 0x4)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x29f
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /Users/amit/go/src/github.com/openshift/odo/cmd/odo/odo.go:73 +0x489
```
```
$ odo config set --ports 8080/TCP
Error: unknown flag: --ports
Usage:
  odo config set [flags]

Examples:

  # Set a configuration value in the local config
  odo config set Type java
  odo config set Name test
  odo config set MinMemory 50M
  odo config set MaxMemory 500M
  odo config set Memory 250M
  odo config set Ignore false
  odo config set MinCPU 0.5
  odo config set MaxCPU 2
  odo config set CPU 1
  
  # Set a env variable in the local config
  odo config set Type --env PORT=4000
  odo config set Name --env DB_USERNAME=postgres,DB_HOSTNAME=postgres
  odo config set MinMemory --env KAFKA_HOST=kafka --env KAFKA_PORT=6639

Flags:
  -e, --env stringSlice   Set the environment variables in config
  -f, --force             Don't ask for confirmation, set the config directly
  -h, --help              help for set

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default false)
      --skip-connection-check            Skip cluster check
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

 ✗  unknown flag: --ports
```

**Comment by kadel** [comment]
this is the result of using empty interfaces :-( 
If the correct type is used it would be caught at compile.
