### ISSUE TITLE
odo create behavior with 'local'

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#1676]
[kind/bug]

## What versions of software are you using?
- Operating System: CentOS Linux release 7.6.1810 (Core)
- Output of `odo version`:
```
$ odo version
odo v1.0.0-beta1 (c226b008)

Server: https://192.168.42.98:8443
Kubernetes: v1.11.0+d4cacc0
```
## How did you run odo exactly?
In the current working directory, I have some code that I would like to run on OpenShift cluster. I did:
```
$ odo component create                                                                                                                         
? Which component type would wish to create python                                                                                                            
? Which version of 'python' component type would you wish to create 3.6                                                                                       
? Location of context component, relative to '/root/django_basic' ./                                                                                          
? Which input type would wish to use for the component local                                                                                                  
? How would you wish to name the new component python-ejpp                                                                                                    
? Which application do you want the commponent to be associated with app                                                                                      
? Which project go you want the component to be created in myproject                                                                                          
? Do you wish to set advanced options No                                                                                                                      
 ✓  Checking component                                                                                                                                        
 ✓  Checking component version                                                                                                                                
Please use `odo push` command to create the component with source deployed                                                                                    
$ odo config view                                                                                                                              
COMPONENT SETTINGS                                                                                                                                            
------------------------------------------------                                                                                                              
PARAMETER         CURRENT_VALUE                                                                                                                               
Type              python:3.6                                                                                                                                  
Application       app                                                                                                                                         
Project           myproject                                                                                                                                   
SourceType        local                                                                                                                                       
Ref                                                                                                                                                           
SourceLocation    /root/django_basic                                                                                                                          
Ports                                                                                                                                                         
Name              python-ejpp                                                                                                                                 
MinMemory                                                                                                                                                     
MaxMemory                                                                                                                                                     
Ignore                                                                                                                                                        
MinCPU
MaxCPU
```

And then did `odo push`. But the container doesn't seem to have any source code:
```
(app-root) sh-4.2$ ls -a
.  ..  .dummy  .pki  .rnd
(app-root) sh-4.2$
```

But if I do just `odo create python` from the same directory, it works. Looking at the config output, I see that `SourceLocation` is set differently in the two cases.
```
$ odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              python
Application       app
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             
Name              python-srnf
MinMemory         
MaxMemory         
Ignore            
MinCPU            
MaxCPU
```

## Actual behavior

The code doesn't get pushed to the container running on OpenShift cluster

## Expected behavior

The code should have been pushed to the container running on OpenShift cluster. Also there's below question being asked during `odo component create`:
```
? Location of context component, relative to '/root/django_basic' ./                                                                                          
```
which I answered as `./` assuming that would help me set same `SourceLocation` when doing `odo component create` but that still set `/root/django_basic` as the path. What's the meaning of `Location of context component`?

**Comment by girishramnani** [comment]
@dharmit could you share the source code repo for `django_basic`?  or was it a boiler plate generated using `django-admin startproject`?

**Comment by jankleinert** [comment]
I am running into a similar issue. entering `/`as source location works, but entering `./`or accepting the default value does not work. Steps to reproduce:

git clone https://github.com/sclorg/nodejs-ex
cd nodejs-ex
odo component create
>>accept all defaults, and enter ./ as the source location
odo push --v 5

You'll see the following -- **see how it's appending the path to itself?**

```
✓  Pushing changes to component: nodejs-ydkk of type local
I0503 15:22:34.398749    3595 push.go:206] Copying directory /opt/app-root/src/nodejs-ex3/opt/app-root/src/nodejs-ex3 to pod
I0503 15:22:34.398759    3595 component.go:626] PushLocal: componentName: nodejs-ydkk, applicationName: app, path: /opt/app-
root/src/nodejs-ex3/opt/app-root/src/nodejs-ex3, files: [], delFiles: [], isForcePush: true
I0503 15:22:34.578678    3595 request.go:485] Throttling request took 179.850335ms, request: GET:https://172.30.0.1:443/apis
/apps.openshift.io/v1/namespaces/developing-with-odo-jan-workshop1-c4696/deploymentconfigs?labelSelector=app.kubernetes.io%2
Fname%3Dapp%2Capp.kubernetes.io%2Fcomponent-name%3Dnodejs-ydkk
I0503 15:22:34.581344    3595 occlient.go:1722] Waiting for deploymentconfig=nodejs-ydkk-app pod
 •  Waiting for component to start  ...
I0503 15:22:36.625726    3595 occlient.go:1746] Status of nodejs-ydkk-app-1-cdj79 pod is Pending
I0503 15:22:36.625907    3595 occlient.go:1746] Status of nodejs-ydkk-app-1-cdj79 pod is Pending
I0503 15:22:36.636708    3595 occlient.go:1746] Status of nodejs-ydkk-app-1-cdj79 pod is Pending
I0503 15:22:40.083507    3595 occlient.go:1746] Status of nodejs-ydkk-app-1-cdj79 pod is Pending
I0503 15:22:41.120529    3595 occlient.go:1746] Status of nodejs-ydkk-app-1-cdj79 pod is Pending
I0503 15:22:42.158929    3595 occlient.go:1746] Status of nodejs-ydkk-app-1-cdj79 pod is Running
 ✓  Waiting for component to start
I0503 15:22:42.158970    3595 occlient.go:1750] Pod nodejs-ydkk-app-1-cdj79 is Running
 •  Copying files to component  ...
I0503 15:22:42.159054    3595 component.go:680] Copying files  to pod
I0503 15:22:42.159065    3595 occlient.go:2784] CopyFile arugments: localPath /opt/app-root/src/nodejs-ex3/opt/app-root/src/
nodejs-ex3, dest /tmp/src/nodejs-ex3, copyFiles [], globalExps [/opt/app-root/src/nodejs-ex3/opt/app-root/src/nodejs-ex3/.gi
t]
I0503 15:22:42.159427    3595 occlient.go:2826] makeTar arguments: srcPath: /opt/app-root/src/nodejs-ex3/opt/app-root/src/no
dejs-ex3, destPath: /tmp/src/nodejs-ex3, files: []
I0503 15:22:42.159446    3595 occlient.go:2891] recursiveTar arguments: srcBase: /opt/app-root/src/nodejs-ex3/opt/app-root/s
rc, srcFile: nodejs-ex3, destBase: /tmp/src, destFile: nodejs-ex3
 ✓  Copying files to component
 •  Building component  ...
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
+ b_IFS='
'
+ b_OFS=
+ OIFS='
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.dummy
+ OIFS=
+ IFS='
'
+ '[' -n rhoar-nodejs/nodejs-10 ']'
+ '[' rhoar-nodejs/nodejs-10 == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source
---> Building your Node application from source
Current git config
url.git@github.com">https://github.com.insteadof=git@github.com:
url.https://.insteadof=ssh://
url.git@github.com">https://github.com.insteadof=ssh://git@github.com
---> Installing dependencies
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:13
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:326:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at evalScript (internal/bootstrap/node.js:589:27)
 ✗  Unable to build files
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
+ b_IFS='
'
+ b_OFS=
+ OIFS='
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /opt/app-root/src/.dummy
+ OIFS=
+ IFS='
'
+ '[' -n rhoar-nodejs/nodejs-10 ']'
+ '[' rhoar-nodejs/nodejs-10 == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source
---> Building your Node application from source
Current git config
url.git@github.com">https://github.com.insteadof=git@github.com:
url.https://.insteadof=ssh://
url.git@github.com">https://github.com.insteadof=ssh://git@github.com
---> Installing dependencies
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:13
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:326:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at evalScript (internal/bootstrap/node.js:589:27)

 ✗  Building component
I0503 15:22:44.417341    3595 cmdutils.go:23] Error:
Failed to push component: nodejs-ydkk: unable to execute assemble script: error while streaming command: command terminated
with exit code 1
 ✗  command terminated with exit code 1
```
odo config view shows:
```
odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs:10
Application       app
Project           developing-with-odo-jan-workshop1-c4696
SourceType        local
Ref
SourceLocation    /opt/app-root/src/nodejs-ex3
Ports
Name              nodejs-ydkk
MinMemory
MaxMemory
Ignore
MinCPU
MaxCPU
```

If you do the same, but enter `/`as the source location, it works.

**Comment by dharmit** [comment]
> @dharmit could you share the source code repo for django_basic? or was it a boiler plate generated using django-admin startproject?

Yes, it's _that_ basic. Just the boilerplate code.

**Comment by cdrage** [comment]
Since I did some changes to detecting the relative path / current path, I'm going to take this up :+1:

**Comment by cdrage** [comment]
PR here, thought I linked it before: https://github.com/openshift/odo/pull/1764
