### ISSUE TITLE
In a disconnected cluster component create throws error of "...tag not found..." though it is listed in catalog list 

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#2333]
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo catalog list components
Odo Supported OpenShift Components:
NAME       PROJECT       TAGS
java       openshift     11,8,latest
nodejs     openshift     8

Odo Unsupported OpenShift Components:
NAME                                    PROJECT       TAGS
dotnet                                  openshift     2.1,2.2,latest
eap-cd-openshift                        openshift     12,12.0,13,13.0,14,14.0,15,15.0,16,16.0,latest
fis-java-openshift                      openshift     1.0,2.0
[...]
```
```
$ odo component create java --project test123 
✗  image stream java with tag latest not found in openshift and test123 namespaces
```

## Actual behavior
Fails

## Expected behavior
Should create

## Any logs, error output, etc?

```
$ odo component create java --project test123 -v9I1030 16:25:53.750916   57694 loader.go:359] Config loaded from file /Users/amit/installerOpenshiftAmit60/auth/kubeconfig
I1030 16:25:53.752341   57694 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: odo/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Authorization: Bearer 6_YzUayJefK572JEB3PRttn_Ic9snrfganQid0r2gmI" 'https://api.preserve-jialiu42-dis.qe.devcluster.openshift.com:6443/apis/project.openshift.io/v1/projects/test123'
I1030 16:25:54.967521   57694 round_trippers.go:405] GET https://api.preserve-jialiu42-dis.qe.devcluster.openshift.com:6443/apis/project.openshift.io/v1/projects/test123 404 Not Found in 1215 milliseconds
I1030 16:25:54.967571   57694 round_trippers.go:411] Response Headers:
I1030 16:25:54.967583   57694 round_trippers.go:414]     Audit-Id: f9aac8a7-2619-4a6b-8057-e8b35596164a
I1030 16:25:54.967592   57694 round_trippers.go:414]     Cache-Control: no-cache, private
I1030 16:25:54.967605   57694 round_trippers.go:414]     Cache-Control: no-store
I1030 16:25:54.967641   57694 round_trippers.go:414]     Content-Type: application/json
I1030 16:25:54.967651   57694 round_trippers.go:414]     Date: Wed, 30 Oct 2019 10:54:41 GMT
I1030 16:25:54.967655   57694 round_trippers.go:414]     Content-Length: 194
I1030 16:25:54.968142   57694 request.go:897] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"test123\" not found","reason":"NotFound","details":{"name":"test123","kind":"namespaces"},"code":404}
I1030 16:25:54.968833   57694 preference.go:118] The path for preference file is /Users/amit/.odo/preference.yaml
I1030 16:25:54.969187   57694 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: odo/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Authorization: Bearer 6_YzUayJefK572JEB3PRttn_Ic9snrfganQid0r2gmI" -H "Accept: application/json, */*" 'https://api.preserve-jialiu42-dis.qe.devcluster.openshift.com:6443/apis/image.openshift.io/v1/namespaces/test123/imagestreams/java'
I1030 16:25:55.249498   57694 round_trippers.go:405] GET https://api.preserve-jialiu42-dis.qe.devcluster.openshift.com:6443/apis/image.openshift.io/v1/namespaces/test123/imagestreams/java 404 Not Found in 280 milliseconds
I1030 16:25:55.249530   57694 round_trippers.go:411] Response Headers:
I1030 16:25:55.249539   57694 round_trippers.go:414]     Content-Type: application/json
I1030 16:25:55.249556   57694 round_trippers.go:414]     Date: Wed, 30 Oct 2019 10:54:41 GMT
I1030 16:25:55.249564   57694 round_trippers.go:414]     Content-Length: 240
I1030 16:25:55.249573   57694 round_trippers.go:414]     Audit-Id: 85dd0644-00ec-425f-9fb6-fe0c2dbd895a
I1030 16:25:55.249581   57694 round_trippers.go:414]     Cache-Control: no-cache, private
I1030 16:25:55.249587   57694 round_trippers.go:414]     Cache-Control: no-store
I1030 16:25:55.249626   57694 request.go:897] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"imagestreams.image.openshift.io \"java\" not found","reason":"NotFound","details":{"name":"java","group":"image.openshift.io","kind":"imagestreams"},"code":404}
I1030 16:25:55.249926   57694 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: odo/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Authorization: Bearer 6_YzUayJefK572JEB3PRttn_Ic9snrfganQid0r2gmI" 'https://api.preserve-jialiu42-dis.qe.devcluster.openshift.com:6443/apis/image.openshift.io/v1/namespaces/openshift/imagestreams/java'
I1030 16:25:55.644772   57694 round_trippers.go:405] GET https://api.preserve-jialiu42-dis.qe.devcluster.openshift.com:6443/apis/image.openshift.io/v1/namespaces/openshift/imagestreams/java 200 OK in 394 milliseconds
I1030 16:25:55.644799   57694 round_trippers.go:411] Response Headers:
I1030 16:25:55.644805   57694 round_trippers.go:414]     Content-Length: 3170
I1030 16:25:55.644809   57694 round_trippers.go:414]     Audit-Id: 05719d14-3eed-45cc-98e6-c1cf09f3cb33
I1030 16:25:55.644814   57694 round_trippers.go:414]     Cache-Control: no-cache, private
I1030 16:25:55.644818   57694 round_trippers.go:414]     Cache-Control: no-store
I1030 16:25:55.644822   57694 round_trippers.go:414]     Content-Type: application/json
I1030 16:25:55.644826   57694 round_trippers.go:414]     Date: Wed, 30 Oct 2019 10:54:42 GMT
I1030 16:25:55.644863   57694 request.go:897] Response Body: {"kind":"ImageStream","apiVersion":"image.openshift.io/v1","metadata":{"name":"java","namespace":"openshift","selfLink":"/apis/image.openshift.io/v1/namespaces/openshift/imagestreams/java","uid":"956e25db-eb34-11e9-ada4-0a580a800012","resourceVersion":"10962","generation":2,"creationTimestamp":"2019-10-10T08:04:28Z","labels":{"samples.operator.openshift.io/managed":"true"},"annotations":{"openshift.io/display-name":"Red Hat OpenJDK 8","openshift.io/image.dockerRepositoryCheck":"2019-10-10T08:05:33Z","openshift.io/provider-display-name":"Red Hat, Inc.","samples.operator.openshift.io/version":"4.2.0-rc.3","version":"1.4.17"}},"spec":{"lookupPolicy":{"local":false},"tags":[{"name":"11","annotations":{"description":"Build and run Java applications using Maven and OpenJDK 11.","iconClass":"icon-rh-openjdk","openshift.io/display-name":"Red Hat OpenJDK 11","sampleContextDir":"undertow-servlet","sampleRepo":"https://github.com/jboss-openshift/openshift-quickstarts","supports":"java:11,java","tags":"builder,java,openjdk","version":"11"},"from":{"kind":"DockerImage","name":"registry.redhat.io/openjdk/openjdk-11-rhel7:latest"},"generation":2,"importPolicy":{},"referencePolicy":{"type":"Local"}},{"name":"8","annotations":{"description":"Build and run Java applications using Maven and OpenJDK 8.","iconClass":"icon-rh-openjdk","openshift.io/display-name":"Red Hat OpenJDK 8","sampleContextDir":"undertow-servlet","sampleRepo":"https://github.com/jboss-openshift/openshift-quickstarts","supports":"java:8,java","tags":"builder,java,openjdk","version":"8"},"from":{"kind":"DockerImage","name":"registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest"},"generation":2,"importPolicy":{},"referencePolicy":{"type":"Local"}},{"name":"latest","annotations":{"description":"Build and run Java applications using Maven and OpenJDK 11.","iconClass":"icon-rh-openjdk","openshift.io/display-name":"Red Hat OpenJDK 11","sampleContextDir":"undertow-servlet","sampleRepo":"https://github.com/jboss-openshift/openshift-quickstarts","supports":"java:11,java","tags":"builder,java,openjdk","version":"latest"},"from":{"kind":"ImageStreamTag","name":"java:11"},"generation":1,"importPolicy":{},"referencePolicy":{"type":"Local"}}]},"status":{"dockerImageRepository":"image-registry.openshift-image-registry.svc:5000/openshift/java","publicDockerImageRepository":"default-route-openshift-image-registry.apps.preserve-jialiu42-dis.qe.devcluster.openshift.com/openshift/java","tags":[{"tag":"11","items":null,"conditions":[{"type":"ImportSuccess","status":"False","lastTransitionTime":"2019-10-10T08:05:33Z","reason":"InternalError","message":"Internal error occurred: Get https://registry.redhat.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","generation":2}]},{"tag":"8","items":null,"conditions":[{"type":"ImportSuccess","status":"False","lastTransitionTime":"2019-10-10T08:05:33Z","reason":"InternalError","message":"Internal error occurred: Get https://registry.redhat.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","generation":2}]}]}}
I1030 16:25:55.647133   57694 cmdutils.go:48] Error:
image stream java with tag latest not found in openshift and test123 namespaces
 ✗  image stream java with tag latest not found in openshift and test123 namespaces
```
```
$ odo preference view
PARAMETER             CURRENT_VALUE
UpdateNotification    
NamePrefix            
Timeout               30
```

**Comment by amitkrout** [comment]
NOTE: I am using a disconnected cluster

**Comment by amitkrout** [comment]
```
$ odo create nodejs:8 nodejs --project test123 --context /home/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs/
 ✗  unable to find tag 8 for image nodejs

$ odo create nodejs:10 nodejs --project test123 --context /home/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs/
 ✗  unable to find tag 10 for image nodejs

$ odo create nodejs:8-RHOAR nodejs --project test123 --context /home/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs/
 ✗  unable to find tag 8-RHOAR for image nodejs
```

@kadel @girishramnani This issue needs your prior attention.

**Comment by kadel** [comment]
@amitkrout When you have disconnected cluster again, can you try to run `oc -n openshift get is nodejs` and paste the output here?

I think that the issue might be that the builder image is not downloaded.

**Comment by amitkrout** [comment]
> can you try to run oc -n openshift get is nodejs and paste the output here?

$ oc -n openshift get is nodejsNAME     IMAGE REPOSITORY                                                    TAGS           UPDATED
nodejs   image-registry.openshift-image-registry.svc:5000/openshift/nodejs   10,8,8-RHOAR

**Comment by amitkrout** [comment]
@mik-dass is looking into this

**Comment by amitkrout** [comment]
Creating a sample oc app fails. Seems there are no image in the cluster. May be some pre config is required for accessing the image in the disconnected cluster. Will check with openshift QE team in the regard how they are testing on such cluster cc_ @mik-dass 
```
$ oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git
W1203 16:50:38.755343   13981 dockerimagelookup.go:236] container image registry lookup failed: docker.io/centos/ruby-25-centos7:latest: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
error: unable to locate any images in image streams, local docker images with name "centos/ruby-25-centos7"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
```

@mik-dass Can you please share your analysis

**Comment by mik-dass** [comment]
@kadel @amitkrout I faced the same error as described in https://github.com/openshift/odo/issues/2333#issuecomment-561149118

I discovered that we check for the presence of the tag in the image stream by checking `imagestream.Status.Tags`
https://github.com/openshift/odo/blob/50c6f73e8c00334f80f67a76f239f60630fb93e5/pkg/occlient/occlient.go#L651

But during listing we use `imagestream.spec.tags` for finding all the tags https://github.com/openshift/odo/blob/50c6f73e8c00334f80f67a76f239f60630fb93e5/pkg/catalog/catalog.go#L310

A mismatch on the disconnected server caused the above issue as the the tag `latest` was not found in the `status.tags`. Also for others like `nodejs:8`, the value of `tag.items` is empty https://github.com/openshift/odo/blob/50c6f73e8c00334f80f67a76f239f60630fb93e5/pkg/occlient/occlient.go#L749
Thus, running creation with other component types like `nodejs:10` etc also fail.

**Comment by amitkrout** [comment]
In the meanwhile i was trying a different usecase where we have images in a separate private registry and these images are part of imagestream in that disconnected cluster. 

```odo catalog list components``` panics out after i applied the is

```
$ podman pull registry.access.redhat.com/openjdk/openjdk-11-rhel7:latest
$ podman tag registry.access.redhat.com/openjdk/openjdk-11-rhel7:latest registry.crt.codereadyqe.com/openshiftdo/openjdk-11-rhel7:latest
$ podman push registry.crt.codereadyqe.com/openshiftdo/openjdk-11-rhel7:latest
$ oc login -u kubeadmin -p ************* https://*****************:6443
$ oc apply -n openshift -f /Users/amit/go/src/github.com/openshift/odo/tests/examples/imagestream.yaml 
imagestream.image.openshift.io/myjava created

$ odo catalog list components
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2038bb1]

goroutine 1 [running]:
github.com/openshift/odo/pkg/catalog.createImageTagMap(0xc0000df3b0, 0x1, 0x1, 0x1)
        /Users/amit/go/src/github.com/openshift/odo/pkg/catalog/catalog.go:259 +0x111
github.com/openshift/odo/pkg/catalog.SliceSupportedTags(0x2587868, 0xd, 0x25977d3, 0x19, 0xc0007b7220, 0x6, 0x0, 0x0, 0xc0007b7230, 0x9, ...)
        /Users/amit/go/src/github.com/openshift/odo/pkg/catalog/catalog.go:229 +0x5a
github.com/openshift/odo/pkg/odo/cli/catalog/list.(*ListComponentsOptions).Run(0xc0004cd180, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/catalog/list/components.go:67 +0x1ec
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x284fc80, 0xc0004cd180, 0xc000991440, 0x39ebcb8, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28 +0x100
github.com/openshift/odo/pkg/odo/cli/catalog/list.NewCmdCatalogListComponents.func1(0xc000991440, 0x39ebcb8, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/catalog/list/components.go:107 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000991440, 0x39ebcb8, 0x0, 0x0, 0xc000991440, 0x39ebcb8)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0009ee240, 0x0, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x29f
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /Users/amit/go/src/github.com/openshift/odo/cmd/odo/odo.go:80 +0x536
Amits-MacBook-Pro:disconnected amit$ odo catalog list components
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2038bb1]

goroutine 1 [running]:
github.com/openshift/odo/pkg/catalog.createImageTagMap(0xc0000f7450, 0x1, 0x1, 0x1)
        /Users/amit/go/src/github.com/openshift/odo/pkg/catalog/catalog.go:259 +0x111
github.com/openshift/odo/pkg/catalog.SliceSupportedTags(0x2587868, 0xd, 0x25977d3, 0x19, 0xc00074df50, 0x6, 0x0, 0x0, 0xc00074df60, 0x9, ...)
        /Users/amit/go/src/github.com/openshift/odo/pkg/catalog/catalog.go:229 +0x5a
github.com/openshift/odo/pkg/odo/cli/catalog/list.(*ListComponentsOptions).Run(0xc000a9de00, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/catalog/list/components.go:67 +0x1ec
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x284fc80, 0xc000a9de00, 0xc0009e6fc0, 0x39ebcb8, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28 +0x100
github.com/openshift/odo/pkg/odo/cli/catalog/list.NewCmdCatalogListComponents.func1(0xc0009e6fc0, 0x39ebcb8, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/catalog/list/components.go:107 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0009e6fc0, 0x39ebcb8, 0x0, 0x0, 0xc0009e6fc0, 0x39ebcb8)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0007738c0, 0x0, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x29f
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /Users/amit/go/src/github.com/openshift/odo/cmd/odo/odo.go:80 +0x536
```
```
$ cat /Users/amit/go/src/github.com/openshift/odo/tests/examples/imagestream.yaml 
kind: "ImageStream"
apiVersion: "v1"
metadata:
  name: "myjava"
  creationTimestamp: null
spec:
  dockerImageRepository: "registry.crt.codereadyqe.com/openshiftdo/openjdk-11-rhel7"
  tags:
    -
      name: "latest"
      annotations:
        description: "Build and run java applications"
        iconClass: "icon-ruby"
        tags: "builder,myjava"
```

**Comment by amitkrout** [comment]
I got the steps of how to login to local registry of a disconnected cluster (hosted on OpenShift QE resources) from Openshift QE member. Unfortunately these steps does not work for me. So pinged them again.

**Comment by amitkrout** [comment]
> I got the steps of how to login to local registry of a disconnected cluster (hosted on OpenShift QE resources) from Openshift QE member. Unfortunately these steps does not work for me. So pinged them again.

I am able to login to the disconnected cluster local registry using the below steps
```
$ oc get secret router-certs-default -n openshift-ingress -o yaml
$ echo <tls.crt_content> | base64 -d > ca.crt
$ sudo cp ca.crt  /etc/pki/ca-trust/source/anchors/<external_route>.crt
$ sudo update-ca-trust enable
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
Then do Docker login <external_registry_route> with your username and token
```

However now i am facing an issue of ```received unexpected HTTP status: 500 Internal Server Error``` while pushing the init image to the local registry.

**Comment by amitkrout** [comment]
> ```
> $ odo catalog list components
> Odo Supported OpenShift Components:
> NAME       PROJECT       TAGS
> java       openshift     11,8,latest
> nodejs     openshift     10,8,8-RHOAR,latest
> 
> Odo Unsupported OpenShift Components:
> NAME                                    PROJECT       TAGS
> dotnet                                  openshift     2.1,2.2,latest
> [...]
> 
> $ odo create nodejs nodejs --project test123 --context /home/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs/
>  ✗  image stream nodejs with tag latest not found in openshift and test123 namespaces
> 
> $ odo create nodejs:8 nodejs --project test123 --context /home/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs/
>  ✗  unable to find tag 8 for image nodejs
> 
> $ odo create nodejs:10 nodejs --project test123 --context /home/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs/
>  ✗  unable to find tag 10 for image nodejs
> 
> $ odo create nodejs:8-RHOAR nodejs --project test123 --context /home/amit/go/src/github.com/openshift/odo/tests/examples/source/nodejs/
>  ✗  unable to find tag 8-RHOAR for image nodejs
> ```
> 
> @kadel @girishramnani This issue needs your prior attention.
> 
> @cdrage Please have a look whenever you have time. I have sent you the details of disconnected cluster to your redhat mail box.

Commented by @wzheng1 - https://github.com/openshift/odo/issues/2189#issuecomment-562465666

**Comment by kadel** [comment]
> @kadel @amitkrout I faced the same error as described in [#2333 (comment)](https://github.com/openshift/odo/issues/2333#issuecomment-561149118)
> 
> I discovered that we check for the presence of the tag in the image stream by checking `imagestream.Status.Tags`
> https://github.com/openshift/odo/blob/50c6f73e8c00334f80f67a76f239f60630fb93e5/pkg/occlient/occlient.go#L651
> 
> But during listing we use `imagestream.spec.tags` for finding all the tags
> 
> https://github.com/openshift/odo/blob/50c6f73e8c00334f80f67a76f239f60630fb93e5/pkg/catalog/catalog.go#L310
> 
> A mismatch on the disconnected server caused the above issue as the the tag `latest` was not found in the `status.tags`. Also for others like `nodejs:8`, the value of `tag.items` is empty
> 
> https://github.com/openshift/odo/blob/50c6f73e8c00334f80f67a76f239f60630fb93e5/pkg/occlient/occlient.go#L749
> 
> 
> Thus, running creation with other component types like `nodejs:10` etc also fail.

This looks like the images are not present in the openshfit  registry.

**Comment by girishramnani** [comment]
> This looks like the images are not present in the openshfit registry.

as per the discussion, it seems this doesn't need to be resolved
