### ISSUE TITLE
odo crashed when running  catalog list components

### ISSUE THREAD

**Issue by jichenjc** [openshift/odo#2628]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

[root@xyimgr77 ~]# ./odo version
odo v1.1.0 (86c7e2c9)

Server: https://api.ocp-test.redhat.com:6443
Kubernetes: v1.14.6+8bbaf43
## How did you run odo exactly?

create 3 image streams, the 2nd and 3rd might share some same info, but can't remember what's changed.. lead to following crash

```
[root@xyimgr77 frontend]# ../odo catalog list components
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/openshift/odo/pkg/catalog.createImageTagMap(0xc0000b2370, 0x1, 0x1, 0xc000628ea0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/catalog/catalog.go:263 +0x37e
github.com/openshift/odo/pkg/catalog.SliceSupportedTags(0x15d2b0a, 0xd, 0x15e340a, 0x19, 0xc0007dffd0, 0x7, 0x0, 0x0, 0xc0007dffe0, 0x9, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/catalog/catalog.go:230 +0x86
github.com/openshift/odo/pkg/odo/cli/catalog/list.(*ListComponentsOptions).Run(0xc000417e00, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/catalog/list/components.go:72 +0x2c4
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x18a3340, 0xc000417e00, 0xc000a27b00, 0x2a4ac90, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x168
github.com/openshift/odo/pkg/odo/cli/catalog/list.NewCmdCatalogListComponents.func1(0xc000a27b00, 0x2a4ac90, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/catalog/list/components.go:112 +0x4e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000a27b00, 0x2a4ac90, 0x0, 0x0, 0xc000a27b00, 0x2a4ac90)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x26c
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000a3c900, 0x16d21e8, 0xc000087ce0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x28e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72 +0x42e
```

**Comment by girishramnani** [comment]
can you share the image stream information? Like possibly the spec of the image stream you created?

**Comment by jichenjc** [comment]
sorry, I didn't notice this question yesterday, I have 3 components (just copy below yml and do some rename of the name ,maybe I have some identical settings forgot to change lead to potential issue?

```
metadata:
  annotations:
    openshift.io/display-name: Red Hat OpenJDK 11
    openshift.io/image.dockerRepositoryCheck: "2019-12-12T06:58:49Z"
    openshift.io/provider-display-name: Red Hat, Inc.
    samples.operator.openshift.io/version: 4.2.10
    version: 1.4.17
  creationTimestamp: "2019-12-12T06:57:57Z"
  generation: 2
  labels:
    samples.operator.openshift.io/managed: "true"
  name: openjdk-11-rhel7
  namespace: openshift
  resourceVersion: "10201"
  selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/openjdk-11-rhel7
  uid: ba6e4ba4-1cac-11ea-be1e-0a580a800025
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 11.
      iconClass: icon-rh-openjdk
      openshift.io/display-name: Red Hat OpenJDK 11
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:11
      tags: builder,java,openjdk
      version: "1.0"
    from:
      kind: DockerImage
      name: registry.redhat.io/openjdk/openjdk-11-rhel7:1.0
    generation: 2
    importPolicy: {}
    name: "1.0"
    referencePolicy:
      type: Local

```
