### ISSUE TITLE
panic: runtime error: slice bounds out of range, when running `odo update --git`

### ISSUE THREAD

**Issue by kadel** [openshift/odo#2646]
```
▶ odo component create java:8 --project myproject
 ✓  Validating component [58ms]

Please use `odo push` command to create the component with source deployed

▶ odo push
Validation
 ✓  Checking component [102ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [387ms]

Pushing to component java-spring-boot-pgbf of type local
 ✓  Checking files for pushing [4ms]
 ✓  Waiting for component to start [1m]
 ✓  Syncing files to the component [621ms]
 ✓  Building component [1m]
 ✓  Changes successfully pushed to component


▶ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java:8
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8443/TCP
  - 8778/TCP
  - 8080/TCP
  Application: app
  Project: myproject
  Name: java-spring-boot-pgbf

▶ odo url create --port 8080
 ✓  URL java-spring-boot-pgbf-8080 created for component: java-spring-boot-pgbf

To create URL on the OpenShift Cluster, please use `odo push`

▶ odo push
Validation
 ✓  Checking component [106ms]

Configuration changes
 ✓  Retrieving component data [126ms]
 ✓  Applying configuration [150ms]

Applying URL changes
 ✓  URL java-spring-boot-pgbf-8080: http://java-spring-boot-pgbf-8080-app-myproject.apps.tkral.devcluster.openshift.com created

Pushing to component java-spring-boot-pgbf of type local
 ✓  Checking file changes for pushing [6ms]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.

▶ odo update --git https://github.com/kadel/spring-boot-http-booster.git

Configuration changes
 ✓  Retrieving component data [310ms]
 ✓  Triggering build from git [110ms]
 ✓  Waiting for build to finish [2m]
 ✗  Applying configuration [68012ns]
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/openshift/odo/pkg/occlient.removeVolumeMountsFromDC(0xc000a76600, 0x21, 0xc0005ca800, 0x1)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/volumes.go:143 +0x479
github.com/openshift/odo/pkg/occlient.removeTracesOfSupervisordFromDC(0xc0005ca800, 0x0, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1649 +0x18b
github.com/openshift/odo/pkg/occlient.(*Client).PatchCurrentDC(0xc00061ebe0, 0x0, 0x0, 0x0, 0x0, 0xc0004ece20, 0x19, 0x0, 0x0, 0x0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1328 +0xb9d
github.com/openshift/odo/pkg/occlient.(*Client).UpdateDCToGit(0xc00061ebe0, 0xc0004ece20, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1476 +0x319
github.com/openshift/odo/pkg/component.Update(0xc00061ebe0, 0xc0005cc6e0, 0x47, 0x2950260, 0x3889230, 0xc000871960, 0xb, 0xc0009945a0, 0x19, 0xc000507710, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:1184 +0x20bc
github.com/openshift/odo/pkg/component.ApplyConfig(0xc00061ebe0, 0xc0005cc6e0, 0x47, 0x2950260, 0x3889230, 0xc000871960, 0xb, 0xc0009945a0, 0x19, 0xc000507710, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:539 +0xbb
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig(0xc000500540, 0x28da620, 0xc000010018, 0x165, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:119 +0x146
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push(0xc000500540, 0x0, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:181 +0xbd
github.com/openshift/odo/pkg/odo/cli/component.(*UpdateOptions).Run(0xc00027ae10, 0x0, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/update.go:152 +0x19d
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x290bde0, 0xc00027ae10, 0xc000750b40, 0xc0006fe1e0, 0x0, 0x2)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/component.NewCmdUpdate.func1(0xc000750b40, 0xc0006fe1e0, 0x0, 0x2)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/update.go:172 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000750b40, 0xc0006fe1a0, 0x2, 0x2, 0xc000750b40, 0xc0006fe1a0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x285
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0007bd200, 0x274a848, 0xc0008e4f60, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2c9
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x460
```

/kind bug
/area component
/priority high

**Comment by kadel** [comment]
I'm able to reproduce this every time
```
 odo update --git https://github.com/openshift-evangelists/Wild-West-Backend

Configuration changes
 ✓  Retrieving component data [879ms]
 ✓  Triggering build from git [216ms]
 ✓  Waiting for build to finish [2m]
 ✗  Applying configuration [2ms]
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/openshift/odo/pkg/occlient.removeVolumeMountsFromDC(0xc000eaeae0, 0x18, 0xc000737000, 0x1)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/volumes.go:143 +0x47a
github.com/openshift/odo/pkg/occlient.removeTracesOfSupervisordFromDC(0xc000737000, 0x0, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1648 +0x18b
github.com/openshift/odo/pkg/occlient.(*Client).PatchCurrentDC(0xc00040e140, 0x0, 0x0, 0x0, 0x0, 0xc000caa500, 0x10, 0x0, 0x0, 0x0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1327 +0xb9d
github.com/openshift/odo/pkg/occlient.(*Client).UpdateDCToGit(0xc00040e140, 0xc000caa500, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/occlient/occlient.go:1475 +0x307
github.com/openshift/odo/pkg/component.Update(0xc00040e140, 0xc000159600, 0x40, 0x28e9100, 0x3816fd8, 0xc000120ce0, 0xb, 0xc000915020, 0x19, 0xc0004e66c0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:1191 +0x1f3a
github.com/openshift/odo/pkg/component.ApplyConfig(0xc00040e140, 0xc000159600, 0x40, 0x28e9100, 0x3816fd8, 0xc000120ce0, 0xb, 0xc000915020, 0x19, 0xc0004e66c0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/component/component.go:538 +0xbb
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig(0xc0002c41c0, 0x2885b40, 0xc0001a8008, 0xc000b17888, 0x1cd4c15)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:119 +0x146
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push(0xc0002c41c0, 0x0, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:181 +0xd0
github.com/openshift/odo/pkg/odo/cli/component.(*UpdateOptions).Run(0xc0008f2af0, 0x0, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/update.go:152 +0x19d
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x28b4f20, 0xc0008f2af0, 0xc000804000, 0xc00069e3a0, 0x0, 0x2)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/component.NewCmdUpdate.func1(0xc000804000, 0xc00069e3a0, 0x0, 0x2)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/pkg/odo/cli/component/update.go:172 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000804000, 0xc00069e380, 0x2, 0x2, 0xc000804000, 0xc00069e380)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x278
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000856000, 0x26f2468, 0xc00004f200, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2c9
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
	/Users/tkral/Code/goenv/odo/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x45b

```

**Comment by cdrage** [comment]
Well, this is interesting.. Because I'm unable to reproduce this at all:

```sh
~/openshift/nodejs-ex  master ✗                                                                                                                                                                                                                              70d ⚑ ◒  
▶ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: hi
  Name: nodejs-nodejs-ex-rmht

~/openshift/nodejs-ex  master ✗                                                                                                                                                                                                                              70d ⚑ ◒  
▶ odo url create --port 8080
 ✓  URL nodejs-nodejs-ex-rmht-8080 created for component: nodejs-nodejs-ex-rmht

To create URL on the OpenShift Cluster, please use `odo push`

~/openshift/nodejs-ex  master ✗                                                                                                                                                                                                                              70d ⚑ ◒  
▶  odo push
Validation
 ✓  Checking component [115ms]

Configuration changes
 ✓  Retrieving component data [157ms]
 ✓  Applying configuration [153ms]

Applying URL changes
 ✓  URL nodejs-nodejs-ex-rmht-8080: http://nodejs-nodejs-ex-rmht-8080-app-hi.e8ca.engint.openshiftapps.com created

Pushing to component nodejs-nodejs-ex-rmht of type local
 ✓  Checking file changes for pushing [559562ns]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.

~/openshift/nodejs-ex  master ✗                                                                                                                                                                                                                             70d ⚑ ◒  ⍉
▶ odo update --git https://github.com/openshift/nodejs-ex.git

Configuration changes
 ✓  Retrieving component data [321ms]
 ✓  Triggering build from git [76ms]
 ✓  Waiting for build to finish [49s]
 ✓  Applying configuration [22s]

Applying URL changes
 ✓  URL nodejs-nodejs-ex-rmht-8080 already exists

Pushing to component nodejs-nodejs-ex-rmht of type git
 ✓  Changes successfully pushed to component
 ✓  The component nodejs-nodejs-ex-rmht was updated successfully

~/openshift/nodejs-ex  master ✗                                                                                                                                                                                                                              70d ⚑ ◒  
▶ cat .odo/config.yaml
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: https://github.com/openshift/nodejs-ex.git
  SourceType: git
  Ports:
  - 8080/TCP
  Application: app
  Project: hi
  Name: nodejs-nodejs-ex-rmht
  Url:
  - Name: nodejs-nodejs-ex-rmht-8080
    Port: 8080
```

And this is using the standard `https://github.com/openshift/nodejs-ex` application.

I'm going to try the Java build next I guess!

**Comment by cdrage** [comment]
Looks like I'm able to reproduce it (sometimes).

For my notes:

Commands ran:

```sh
git clone https://github.com/spring-projects/spring-petclinic
odo create java --port 8080
odo url create
odo push
odo update --git https://github.com/spring-projects/spring-petclinic
```

Here is the output specifically from `odo update`:


```sh
~/openshift/spring-petclinic  master ✗                                                                                                                                                                                                                                 8d ⚑ ◒  ⍉ 
▶ odo update --git https://github.com/spring-projects/spring-petclinic -v 4                                                                                                                                                                                                      
I0407 14:56:47.503335   19087 preference.go:165] The path for preference file is /home/wikus/.odo/preference.yaml                                                                                                                                                                
I0407 14:56:47.705840   19087 occlient.go:2731] Getting DeploymentConfig: java-spring-petcl-czfz-app                                                                                                                                                                             
                                                                                                                                                                                                                                                                                 
Configuration changes                                                                                                                                                                                                                                                            
I0407 14:56:47.749209   19087 preference.go:165] The path for preference file is /home/wikus/.odo/preference.yaml                                                                                                                                                                
 •  Retrieving component data  ...                                                                                                                                                                                                                                               
I0407 14:56:47.823357   19087 occlient.go:2731] Getting DeploymentConfig: java-spring-petcl-czfz-app                                                                                                                                                                             
I0407 14:56:47.858422   19087 component.go:1031] Source for component java-spring-petcl-czfz is  (local)                                                                                                                                                                         
I0407 14:56:47.858446   19087 occlient.go:2731] Getting DeploymentConfig: java-spring-petcl-czfz-app                                                                                                                                                                             
I0407 14:56:47.895648   19087 component.go:1160] Updating component java-spring-petcl-czfz, from local to https://github.com/spring-projects/spring-petclinic (git).                                                                                                             
I0407 14:56:47.895667   19087 component.go:1170] Creating BuildConfig java-spring-petcl-czfz-app using imageName: java for updating                                                                                                                                              
I0407 14:56:47.970658   19087 occlient.go:3022] Using namespace: openshift for the CreateBuildConfig function                                                                                                                                                                    
 ✓  Retrieving component data [269ms]                                                                                                                                                                                                                                            
 •  Triggering build from git  ...                                                                                                                                                                                                                                               
I0407 14:56:48.018814   19087 occlient.go:1713] Build java-spring-petcl-czfz-app started.                                                                                                                                                                                        
I0407 14:56:48.094289   19087 occlient.go:1723] Build java-spring-petcl-czfz-app for BuildConfig java-spring-petcl-czfz-app-1 triggered.                                                                                                                                         
 ✓  Triggering build from git [75ms]                                                                                                                                                                                                                                             
 •  Waiting for build to finish  ...                                                                                                                                                                                                                                             
I0407 14:56:48.094334   19087 occlient.go:1732] Waiting for java-spring-petcl-czfz-app-1  build to finish                                                                                                                                                                        
I0407 14:56:48.135424   19087 occlient.go:1752] Status of java-spring-petcl-czfz-app-1 build is Pending
I0407 14:56:51.800531   19087 occlient.go:1752] Status of java-spring-petcl-czfz-app-1 build is Running
Cloning "https://github.com/spring-projects/spring-petclinic" ...
        Commit: 56f09331aa627fe8e07d5f3b20e1ec50f2828fb4 (Merge pull request #586 from jelliotartz)
        Author: Stephane Nicoll <snicoll@pivotal.io>
        Date:   Mon Mar 30 08:53:42 2020 +0200
Using 172.30.16.196:5000/openshift/java@sha256:b78b239a8fc0d117fb5bea5366cd02335cc4fe421e071660f0814feecc98d269 as the s2i builder image
BLAH BLAH BLAH BUILD OUTPUT
BLAH BLAH BLAH BUILD OUTPUT
BLAH BLAH BLAH BUILD OUTPUT
I0407 14:58:44.598102   19087 occlient.go:1752] Status of java-spring-petcl-czfz-app-1 build is Running
I0407 14:58:44.598399   19087 occlient.go:1752] Status of java-spring-petcl-czfz-app-1 build is Running
I0407 14:58:44.598544   19087 occlient.go:1752] Status of java-spring-petcl-czfz-app-1 build is Running
I0407 14:58:44.598751   19087 occlient.go:1752] Status of java-spring-petcl-czfz-app-1 build is Complete
I0407 14:58:44.598756   19087 occlient.go:1756] Build java-spring-petcl-czfz-app-1 completed.
 ✓  Waiting for build to finish [2m]
 •  Applying configuration  ...
I0407 14:58:44.598830   19087 component.go:1189] Updating the DeploymentConfig java-spring-petcl-czfz-app image to java-spring-petcl-czfz-app:latest
 ✗  Applying configuration [28418ns]
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/openshift/odo/pkg/occlient.removeVolumeMountsFromDC(0xc0009ee690, 0x22, 0xc000530600, 0x1)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/occlient/volumes.go:143 +0x479
github.com/openshift/odo/pkg/occlient.removeTracesOfSupervisordFromDC(0xc000530600, 0x0, 0x0)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/occlient/occlient.go:1685 +0x18b
github.com/openshift/odo/pkg/occlient.(*Client).PatchCurrentDC(0xc000864d20, 0x0, 0x0, 0x0, 0x0, 0xc000ba9c80, 0x1a, 0x0, 0x0, 0x0, ...)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/occlient/occlient.go:1364 +0xb9d
github.com/openshift/odo/pkg/occlient.(*Client).UpdateDCToGit(0xc000864d20, 0xc000ba9c80, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/occlient/occlient.go:1512 +0x319
github.com/openshift/odo/pkg/component.Update(0xc000864d20, 0xc000aa5480, 0x37, 0x1f12400, 0x2f2d8c0, 0xc000be9a70, 0xb, 0xc000c543a0, 0x19, 0xc000c4f050, ...)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/component/component.go:1195 +0x1f4d
github.com/openshift/odo/pkg/component.ApplyConfig(0xc000864d20, 0x0, 0xc000aa5480, 0x37, 0x1f12400, 0x2f2d8c0, 0xc000be9a70, 0xb, 0xc000c543a0, 0x19, ...)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/component/component.go:546 +0x34b
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig(0xc00038db90, 0x1e955e0, 0xc000010018, 0x0, 0x200)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:128 +0x175
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push(0xc00038db90, 0x0, 0x0)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:190 +0xc3
github.com/openshift/odo/pkg/odo/cli/component.(*UpdateOptions).Run(0xc00076cb90, 0x0, 0x0)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/component/update.go:152 +0x1a5
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x1ec9c20, 0xc00076cb90, 0xc000765440, 0xc00091fdc0, 0x0, 0x4)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/component.NewCmdUpdate.func1(0xc000765440, 0xc00091fdc0, 0x0, 0x4)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/component/update.go:172 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000765440, 0xc00091fd80, 0x4, 0x4, 0xc000765440, 0xc00091fd80)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x285
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000810000, 0x1cdc648, 0xc00004b4a0, 0x0)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2c9
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x460
```

**Comment by dharmit** [comment]
Unrelated to this issue but `odo update` failed due to a timeout for me:
```sh
                                                                                                                                                                                              
Pushing image image-registry.openshift-image-registry.svc:5000/myproject/java-spring-boot-zjue-app:latest ...                                                                                 
Getting image source signatures                                                                                                                                                               
Copying blob sha256:dca9e5aa183958da75f0d8ccac00be639afd7e6c5aa60810280fb78f6a9d0685                                                                                                          
Copying blob sha256:6c85ac87d44df4b64d7c273886fc5aed55a28422df33dcb641884ffa419db218                                                                                                          
Copying blob sha256:51e9f237b750efcda2d5755785cdb8dd080d51585ae35d368e4f9b29a11b1994                                                                                                          
Copying blob sha256:41bc10dbb03d6e2f00d82a33d2fdfca62e3a50cd17b8efdfa59cbeb650e278af                                                                                                          
Copying config sha256:e4105c16683f5c63a1d998a60385b0430c45ae0df9dd3e1a9064ffb9014197c9                                                                                                        
Writing manifest to image destination                                                                                                                                                         
Storing signatures                                                                                                                                                                            Successfully pushed image-registry.openshift-image-registry.svc:5000/myproject/java-spring-boot-zjue-app@sha256:66e2a903245603c502a0efa29df2bfea6a6b8045e93955633bf6278473181240              
Push successful                                                                                                                                                                               
: timeout waiting for build java-spring-boot-zjue-app-1 to start                                                                                                                              
                     
```

What should I do next? If I run the same `odo update` command, it fails:
```sh
$ odo update --git https://github.com/kadel/spring-boot-http-booster.git                       
                                                                                                                                                                                              Configuration changes                          
 ✗  Retrieving component data [70ms]
 ✗  Failed To Update Config To Component Deployed.                                             
Error: unable to update BuildConfig  for java-spring-boot-zjue component: unable to create BuildConfig for java-spring-boot-zjue-app: buildconfigs.build.openshift.io "java-spring-boot-zjue-a
pp" already exists
```

If I do `odo push` or `odo push -f`, it fails:
```sh
$ odo push
Validation
 ✓  Checking component [25ms]

Configuration changes
 ✗  Retrieving component data [73ms]
 ✗  Failed To Update Config To Component Deployed.
Error: unable to update BuildConfig  for java-spring-boot-zjue component: unable to create BuildConfig for java-spring-boot-zjue-app: buildconfigs.build.openshift.io "java-spring-boot-zjue-app" already exists

$ odo push -f
Validation
 ✓  Checking component [15ms]

Configuration changes
 ✗  Retrieving component data [55ms]
 ✗  Failed To Update Config To Component Deployed.
Error: unable to update BuildConfig  for java-spring-boot-zjue component: unable to create BuildConfig for java-spring-boot-zjue-app: buildconfigs.build.openshift.io "java-spring-boot-zjue-app" already exists
```
What should a user do in such a scenario? As a user, I don't see any message from `odo` that would help me understand what I should do next.
