### ISSUE TITLE
'odo describe' fails for component with two URLs with 'panic: runtime error: index out of range' error

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#2776]
/kind bug

## What versions of software are you using?

**Operating System:** 
Windows 10
**Output of `odo version`:**
odo v1.1.1 (02fbd3d08)

## How did you run odo exactly?
Not pushed git component with two URLs.

## Actual behavior
```
> odo.exe" describe
Component Name: nodejs-ex-git
Type: nodejs:10
Source: https://github.com/dgolovin/nodejs-ex
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/util.PrintComponentInfo(0xc0007afe00, 0xc0001cfab0, 0xd, 0x1befd6d, 0x9, 0x1c09821, 0x19, 0xc0001cfab0, 0xd, 0x0, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/util/cmdutils.go:144 +0x151a
github.com/openshift/odo/pkg/odo/cli/component.(*DescribeOptions).Run(0xc000830300, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:86 +0x2f1
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x1f2a920, 0xc000830300, 0xc0008a8900, 0x3285110, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x143
github.com/openshift/odo/pkg/odo/cli/component.NewCmdDescribe.func1(0xc0008a8900, 0x3285110, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:104 +0x65
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0008a8900, 0x3285110, 0x0, 0x0, 0xc0008a8900, 0x3285110)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x290
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0006c9b00, 0x1d1bfd0, 0xc000074b40, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2d1
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x46a
```

## Expected behavior
Prints out two urls.

## Any logs, error output, etc?
N/A

**Comment by dharmit** [comment]
Besides the original issue mentioned by @dgolovin, I found one more issue in `odo describe` for an unpushed component.

1. Create a component that exposes one port (8080 in below example)
2. Create a URL for that component
3. Do `odo describe`. This correctly shows that URL will be exposed via port 8080
4. Use `odo config set` to add one more exposed port for the component
5. Do `odo describe`. This incorrectly shows the new port as the one being exposed. 

This happens because it picks the first port in the `.odo/config.yaml`. If I had used `odo config set ports 8080/TCP,9090/TCP -f` to change the odo configuration, it would have not showed an erroneous output.

```sh
$ odo create nodejs
Validation       
 ✓  Validating component [7ms]
                                               
Please use `odo push` command to create the component with source deployed
                                               
$ odo url create url1
 ✓  URL url1 created for component: nodejs-nodejs-ex-hizx

To apply the URL configuration changes, please use `odo push`

$ odo describe
Component Name: nodejs-nodejs-ex-hizx
Type: nodejs
Source: file://./
URLs:
 · URL named url1 will be exposed via 8080/TCP  <--------------

$ odo config view                          
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs
Application       app
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             8080/TCP   <--------------
Name              nodejs-nodejs-ex-hizx
MinMemory         
MaxMemory         
DebugPort         
Ignore            
MinCPU            
MaxCPU            

$ odo config set ports 9090/TCP,8080/TCP -f
 ✓  Local config successfully updated

Run `odo push --config` command to apply changes to the cluster

$ odo describe
Component Name: nodejs-nodejs-ex-hizx
Type: nodejs
Source: file://./
URLs:
 · URL named url1 will be exposed via 9090/TCP  <--------------

$ odo config view
COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs
Application       app
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             9090/TCP,8080/TCP   <--------------
Name              nodejs-nodejs-ex-wbth
MinMemory         
MaxMemory         
DebugPort         
Ignore            
MinCPU            
MaxCPU
```
