### ISSUE TITLE
make test fails with experimental mode on

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#2816]
/kind bug

Turn on experimental mode on and run make test

## Actual behavior

```
[mrinaldas@localhost odo]$ go test pkg/url/url.go pkg/url/url_test.go pkg/url/types.go  -count=1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x1141eb9]

goroutine 7 [running]:
testing.tRunner.func1(0xc000231800)
        /usr/local/go/src/testing/testing.go:830 +0x392
panic(0x171b820, 0x2c66460)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/openshift/odo/pkg/kclient.(*Client).CreateIngress(0xc000567f58, 0x18f8198, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mrinaldas/go/src/github.com/openshift/odo/pkg/kclient/ingress.go:21 +0x169
command-line-arguments.Create(0xc0000fe820, 0xc000567f58, 0x18f8198, 0x6, 0x1f90, 0x0, 0x18f8198, 0x6, 0x18f69fe, 0x3, ...)
        /home/mrinaldas/go/src/github.com/openshift/odo/pkg/url/url.go:156 +0x7d1
command-line-arguments.TestCreate.func1(0xc000231800)
        /home/mrinaldas/go/src/github.com/openshift/odo/pkg/url/url_test.go:166 +0x4f8
testing.tRunner(0xc000231800, 0xc00034a010)
        /usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:916 +0x35a
FAIL    command-line-arguments  0.020s
```

## Expected behavior

unit tests should pass without failure

**Comment by amitkrout** [comment]
@mik-dass Thanks for the issue.
Yup, i can see the same failure
