### ISSUE TITLE
Panic if invalid component name is entered during `odo create`

### ISSUE THREAD

**Issue by johnmcollier** [openshift/odo#2826]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
master

## How did you run odo exactly?
I was trying to pull down the open liberty devfile and use it with a sample project. When I ran `odo create openliberty`, I got the following error:
```
Johns-MacBook-Pro-3:openLiberty johncollier$ odo create openliberty
 ✗  Checking if the specified component type is supported devfile component type [76119ns]

Please run 'odo catalog list components' for a list of supported devfile component types
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x22ed14e]

goroutine 1 [running]:
github.com/openshift/odo/pkg/config.(*LocalConfigInfo).ConfigFileExists(...)
	/Users/johncollier/go/src/github.com/openshift/odo/pkg/config/config.go:324
github.com/openshift/odo/pkg/odo/cli/component.(*CreateOptions).Complete(0xc0001b63c0, 0xc00090c240, 0x6, 0xc0004066c0, 0xc00055a5e0, 0x1, 0x1, 0x2, 0x288a1df)
	/Users/johncollier/go/src/github.com/openshift/odo/pkg/odo/cli/component/create.go:408 +0x67e
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2beb700, 0xc0001b63c0, 0xc0004066c0, 0xc00055a5e0, 0x1, 0x1)
	/Users/johncollier/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:29 +0xb8
github.com/openshift/odo/pkg/odo/cli/component.NewCmdCreate.func1(0xc0004066c0, 0xc00055a5e0, 0x1, 0x1)
	/Users/johncollier/go/src/github.com/openshift/odo/pkg/odo/cli/component/create.go:709 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004066c0, 0xc00055a5c0, 0x1, 0x1, 0xc0004066c0, 0xc00055a5c0)
	/Users/johncollier/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00043bb00, 0x0, 0x0, 0x0)
	/Users/johncollier/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/johncollier/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
	/Users/johncollier/go/src/github.com/openshift/odo/cmd/odo/odo.go:83 +0x5c8
```

But if I run `odo create openLiberty`, everything runs fine:
```
Johns-MacBook-Pro-3:openLiberty johncollier$ odo create openLiberty
 ✓  Checking if the specified component type is supported devfile component type [426344ns]
 ✓  Validating component [111322ns]

Please use `odo push` command to create the component with source deployed
```

/area devfile

**Comment by johnmcollier** [comment]
Found the cause of the bug, when `experimental` is set to true, we're returning a partially created CLI context:

https://github.com/openshift/odo/blob/master/pkg/odo/genericclioptions/context.go#L418-L432

**Comment by GeekArthur** [comment]
I am pretty sure the use case `creating s2i component with experimental mode enabled` works before, the root cause this PR #2762 causes the regression as it modifies the context creation function that is used by s2i component. With that changes, currently If user wants to create s2i component with experimental mode enabled, it goes to devfile context code path instead of s2i context code path. We should separate the context for s2i and devfile to fix this.

Thanks @johnmcollier points that out

**Comment by GeekArthur** [comment]
FWIW, we call the context creation function here https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L396 during `odo create`
