### ISSUE TITLE
odo create nodejs-10-rhel7 crashed

### ISSUE THREAD

**Issue by jichenjc** [openshift/odo#2853]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

compiled version

commit cef105be1d519754bde6a5f3cc2b8cc23c49f774
Author: Mrinal Das <mrinald7@gmail.com>
Date:   Wed Apr 8 07:42:00 2020 +0530

## How did you run odo exactly?

run this command with devfile flag=true and got following error

`Updated: I guess I found the root cause, will work on it`
/assign

```
[root@jck8s5 odo]# odo create nodejs-10-rhel7
 ✗  Checking if the specified component type is supported devfile component type [49651ns]

Please run 'odo catalog list components' for a list of supported devfile component types
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x15a6df8]

goroutine 1 [running]:
github.com/openshift/odo/pkg/config.(*LocalConfigInfo).ConfigFileExists(...)
        /root/go/src/github.com/openshift/odo/pkg/config/config.go:324
github.com/openshift/odo/pkg/odo/cli/component.(*CreateOptions).Complete(0xc000705860, 0xc0008da0c0, 0x6, 0xc00087e900, 0xc00068a3e0, 0x1, 0x1, 0xc0000bb2c0, 0x2)
        /root/go/src/github.com/openshift/odo/pkg/odo/cli/component/create.go:413 +0x5c8
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x1e0ee40, 0xc000705860, 0xc00087e900, 0xc00068a3e0, 0x1, 0x1)
        /root/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:29 +0xb8
github.com/openshift/odo/pkg/odo/cli/component.NewCmdCreate.func1(0xc00087e900, 0xc00068a3e0, 0x1, 0x1)
        /root/go/src/github.com/openshift/odo/pkg/odo/cli/component/create.go:743 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc00087e900, 0xc00068a3c0, 0x1, 0x1, 0xc00087e900, 0xc00068a3c0)
        /root/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x278
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0008c7440, 0x1c26ae0, 0xc00015e000, 0x0)
        /root/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2c9
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /root/go/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x45b
```

**Comment by jichenjc** [comment]
```
[root@jck8s5 odo]# odo catalog list components
Odo Devfile Components:
NAME                 DESCRIPTION                           SUPPORTED
maven                Upstream Maven and OpenJDK 11         YES
nodejs               Stack with NodeJS 10                  YES
openLiberty          Open Liberty microservice in Java     YES
java-spring-boot     Spring Boot® using IBM Java           YES
```

**Comment by adisky** [comment]
same as https://github.com/openshift/odo/issues/2826
