### ISSUE TITLE
Multiple Travis failures for "service, link, component sub-commands command integration" tests

### ISSUE THREAD

**Issue by dharmit** [openshift/odo#2955]
I saw multiple Travis failures for **service, link, component sub-commands command integration tests**. 

**First occurrence**
This failure happened because even after 1 minute of doing `odo app delete`, the underlying service in that app was not deleted. I'm not sure if we can add timeout for a longer period. But I've not seen this fail in the past.
```
Failure [106.843 seconds]
odo service command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:15
  When the application is deleted
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:439
    should delete the service(s) in the application as well [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:444
    Timeout out after 1 minutes
```
**Second occurrence**
Doesn't look related to our code to me. 
```
Collecting pip==19.3.1
[odo]   Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
[odo] Installing collected packages: pip
[odo]   Found existing installation: pip 9.0.1
[odo]     Uninstalling pip-9.0.1:
[odo]       Successfully uninstalled pip-9.0.1
[odo] Successfully installed pip-19.3.1
[odo] ---> Installing dependencies ...
[odo] Collecting gunicorn
[odo]   Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
[odo] Collecting numpy
[odo]   Downloading https://files.pythonhosted.org/packages/3d/fc/4763e5f17ac6e7e7d55f377cde859ca1c5d5ac624441ab45315bc578aa9e/numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl (20.2MB)
[odo] ERROR: Exception:
[odo] Traceback (most recent call last):
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
[odo]     yield
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
[odo]     data = self._fp.read(amt) if not fp_closed else b""
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 459, in read
[odo]     n = self.readinto(b)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 503, in readinto
[odo]     n = self.fp.readinto(b)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 586, in readinto
[odo]     return self._sock.recv_into(b)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1012, in recv_into
[odo]     return self.read(nbytes, buffer)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 874, in read
[odo]     return self._sslobj.read(len, buffer)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 631, in read
[odo]     v = self._sslobj.read(len, buffer)
[odo] ConnectionResetError: [Errno 104] Connection reset by peer
[odo] 
[odo] During handling of the above exception, another exception occurred:
[odo] 
[odo] Traceback (most recent call last):
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
[odo]     status = self.run(options, args)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 382, in run
[odo]     resolver.resolve(requirement_set)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
[odo]     self._resolve_one(requirement_set, req)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
[odo]     abstract_dist = self._get_abstract_dist_for(req_to_install)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
[odo]     req, self.session, self.finder, self.require_hashes
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
[odo]     progress_bar=self.progress_bar
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 465, in unpack_url
[odo]     progress_bar=progress_bar
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
[odo]     progress_bar)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 551, in _download_http_url
[odo]     _download_url(resp, link, content_file, hashes, progress_bar)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 253, in _download_url
[odo]     hashes.check_against_chunks(downloaded_chunks)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
[odo]     for chunk in chunks:
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 223, in written_chunks
[odo]     for chunk in chunks:
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 160, in iter
[odo]     for x in it:
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 212, in resp_read
[odo]     decode_content=False):
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
[odo]     data = self.read(amt=amt, decode_content=decode_content)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
[odo]     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
[odo]     self.gen.throw(type, value, traceback)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
[odo]     raise ProtocolError("Connection broken: %r" % e, e)
[odo] pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
[odo] WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
[odo] You should consider upgrading via the 'pip install --upgrade pip' command.
[odo] 
[odo]  ✗  command terminated with exit code 2
Deleting dir: /tmp/624345455
Deleting dir: /tmp/489211394
Deleting project: liajoweoqm
Running odo with args [odo project delete liajoweoqm -f]
[odo] This project contains the following applications, which will be deleted
[odo] Application app
[odo] This application has following components that will be deleted
[odo] component named backend
[odo] component named frontend
[odo]  •  Deleting project liajoweoqm  ...
 ✓  Deleting project liajoweoqm [7s]
[odo]  ✓  Deleted project : liajoweoqm
Deleting dir: /tmp/034198608
• Failure [67.153 seconds]
odo link and unlink command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When link between components using wrong port
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:55
    should fail [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:64
    No future change is possible.  Bailing out early after 22.976s.
    Running odo with args [odo push --context /tmp/489211394]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```
**Third occurrence**
```
Running odo with args [odo component list --app app --project vhbtrcozvq]
[odo]  ✗  invalid configuration: no configuration has been provided
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration
Deleting project: vhbtrcozvq
Running odo with args [odo project delete vhbtrcozvq -f]
[odo]  •  Deleting project vhbtrcozvq  ...
 ✓  Deleting project vhbtrcozvq [7s]
[odo]  ✓  Deleted project : vhbtrcozvq
Deleting dir: /tmp/244880333
• Failure [42.418 seconds]
odo sub component command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
  when component is in the current directory and --project flag is used
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:512
    creates a local python component, pushes it and then deletes it using --all flag in local directory [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:560
    No future change is possible.  Bailing out early after 0.204s.
    Running odo with args [odo component list --app app --project vhbtrcozvq]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

/kind flake
_Originally posted by @dharmit in https://github.com/openshift/odo/pull/2944#issuecomment-617655352_

**Comment by dharmit** [comment]
Hitting `odo app delete` (First occurrence in original issue description) issue again:
```
[oc] NAME                CLASS                                   PLAN      STATUS           AGE
[oc] dh-postgresql-apb   ClusterServiceClass/dh-postgresql-apb   dev       Deprovisioning   2m
• Failure [146.789 seconds]
odo service command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:15
  When the application is deleted
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:439
    should delete the service(s) in the application as well [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:444
    Timeout out after 1 minutes
    /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_generic.go:48
```

**Comment by dharmit** [comment]
A different error this time. Fails to build the maven project for #2944 
```
[odo] [INFO] Downloading: https://repo.spring.io/snapshot/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar
[odo] [INFO] ------------------------------------------------------------------------
[odo] [INFO] BUILD FAILURE
[odo] [INFO] ------------------------------------------------------------------------
[odo] [INFO] Total time: 42.382 s
[odo] [INFO] Finished at: 2020-04-22T10:30:18Z
[odo] [INFO] Final Memory: 16M/53M
[odo] [INFO] ------------------------------------------------------------------------
[odo] [ERROR] Failed to execute goal on project demo: Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: Could not transfer artifact org.mockito:mockito-core:jar:1.10.19 from/to central (https://repo1.maven.org/maven2): GET request of: org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar from central failed: Connection reset -> [Help 1]
[odo] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project demo: Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: Could not transfer artifact org.mockito:mockito-core:jar:1.10.19 from/to central (https://repo1.maven.org/maven2): GET request of: org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar from central failed
[odo] 	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
[odo] 	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:128)
[odo] 	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
[odo] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
[odo] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[odo] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[odo] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[odo] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[odo] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[odo] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[odo] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[odo] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[odo] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[odo] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
[odo] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
[odo] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
[odo] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[odo] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[odo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[odo] 	at java.lang.reflect.Method.invoke(Method.java:498)
[odo] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[odo] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[odo] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[odo] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[odo] Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: Could not transfer artifact org.mockito:mockito-core:jar:1.10.19 from/to central (https://repo1.maven.org/maven2): GET request of: org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar from central failed
[odo] 	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:209)
[odo] 	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
[odo] 	... 23 more
[odo] Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact org.mockito:mockito-core:jar:1.10.19 from/to central (https://repo1.maven.org/maven2): GET request of: org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar from central failed
[odo] 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:393)
[odo] 	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:202)
[odo] 	... 24 more
[odo] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.mockito:mockito-core:jar:1.10.19 from/to central (https://repo1.maven.org/maven2): GET request of: org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar from central failed
[odo] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
[odo] 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
[odo] 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:376)
[odo] 	... 25 more
[odo] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.mockito:mockito-core:jar:1.10.19 from/to central (https://repo1.maven.org/maven2): GET request of: org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar from central failed
[odo] 	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
[odo] 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
[odo] 	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
[odo] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[odo] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[odo] 	at java.lang.Thread.run(Thread.java:748)
[odo] Caused by: org.apache.maven.wagon.TransferFailedException: GET request of: org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar from central failed
[odo] 	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:363)
[odo] 	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:316)
[odo] 	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:285)
[odo] 	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
[odo] 	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
[odo] 	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:569)
[odo] 	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:436)
[odo] 	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:413)
[odo] 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
[odo] 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
[odo] 	... 4 more
[odo] Caused by: java.net.SocketException: Connection reset
[odo] 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
[odo] 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[odo] 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
[odo] 	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
[odo] 	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
[odo] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
[odo] 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
[odo] 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
[odo] 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
[odo] 	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
[odo] 	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
[odo] 	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
[odo] 	at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:531)
[odo] 	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:353)
[odo] 	... 13 more
[odo] [ERROR] 
[odo] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[odo] [ERROR] 
[odo] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[odo] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[odo] Aborting due to error code 1 for Maven build
[odo] 
[odo]  ✗  command terminated with exit code 1
[odo]  ✗  Building component [46s]
Deleting project: urndhzizle
Running odo with args [odo project delete urndhzizle -f]
[odo] This project contains the following applications, which will be deleted
[odo] Application app
[odo] This application has following components that will be deleted
[odo] component named sb-app
[odo] This component has following urls that will be deleted with component
[odo] URL named sb-app-8080 with host sb-app-8080-app-urndhzizle.127.0.0.1.nip.io having protocol http at port 8080
[odo]  •  Deleting project urndhzizle  ...
 ✓  Deleting project urndhzizle [8s]
[odo]  ✓  Deleted project : urndhzizle
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog
Deleting dir: /tmp/727307853
• Failure [133.609 seconds]
odo service command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:15
  When creating with a spring boot application
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:132
    should be able to create postgresql and link it with springboot [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:146
    No future change is possible.  Bailing out early after 116.054s.
    Running odo with args [odo push]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

**Comment by amitkrout** [comment]
> Collecting pip==19.3.1
[odo]   Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
[odo] Installing collected packages: pip
[odo]   Found existing installation: pip 9.0.1
[odo]     Uninstalling pip-9.0.1:
[odo]       Successfully uninstalled pip-9.0.1
[odo] Successfully installed pip-19.3.1
[odo] ---> Installing dependencies ...
[odo] Collecting gunicorn
[odo]   Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
[odo] Collecting numpy
[odo]   Downloading https://files.pythonhosted.org/packages/3d/fc/4763e5f17ac6e7e7d55f377cde859ca1c5d5ac624441ab45315bc578aa9e/numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl (20.2MB)
[odo] ERROR: Exception:
[odo] Traceback (most recent call last):

Build panic out. May be it happens because it builds the package which are not downloaded properly due to some network glitch hence panic out.

> [odo] [INFO] Downloading: https://repo.spring.io/snapshot/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar
[odo] [INFO] ------------------------------------------------------------------------
[odo] [INFO] BUILD FAILURE
[odo] [INFO] ------------------------------------------------------------------------
[odo] [INFO] Total time: 42.382 s
[odo] [INFO] Finished at: 2020-04-22T10:30:18Z
[odo] [INFO] Final Memory: 16M/53M
[odo] [INFO] ------------------------------------------------------------------------
[odo] [ERROR] Failed to

Not related to our code. Throws build mvn error because it builds on the package which are not downloaded properly due to some network glitch.

> Failure [106.843 seconds]
odo service command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:15
  When the application is deleted
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:439
    should delete the service(s) in the application as well [It]
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:444
    Timeout out after 1 minutes

Unfortunately here we missed the full failure log. Anyway will wait for the next occurrence for full failure log.

Now the issue looks more specific. May be due to four test runs in parallel causing slow down. @dharmit Can you please update the issue title to something like ``` On four test node app delete takes more than 1 min```

**Comment by amitkrout** [comment]
> @dharmit Can you please update the issue title to something like On four test node app delete takes more than 1 min

ping @dharmit

**Comment by dharmit** [comment]
Closing since we have a larger issue at hands #4253 

/close
