### ISSUE TITLE
Flakey url_test.go test causing release issues.

### ISSUE THREAD

**Issue by cdrage** [openshift/odo#3017]
/kind bug

```sh
?       github.com/openshift/odo/pkg/testingutil/filesystem     [no test files]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1896782]

goroutine 11 [running]:
testing.tRunner.func1(0xc00049ab00)
        /usr/local/go/src/testing/testing.go:874 +0x69f
panic(0x21b8b60, 0x36659f0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/openshift/odo/pkg/kclient.(*Client).GetDeploymentByName(0xc000573ed8, 0x23aa144, 0x6, 0x2, 0x2, 0xc00063a248)                                                             
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/kclient/deployments.go:29 +0x62                                                                          
github.com/openshift/odo/pkg/url.Create(0xc0002400a0, 0xc000573ed8, 0x23aa144, 0x6, 0x1f90, 0x0, 0x23aa144, 0x6, 0x23a88d2, 0x3, ...)                                                
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/url/url.go:123 +0x476                                                                                    
github.com/openshift/odo/pkg/url.TestCreate.func1(0xc00049ab00)
        /home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/url/url_test.go:166 +0x7f1                                                                               
testing.tRunner(0xc00049ab00, 0xc00036b040)
        /usr/local/go/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:960 +0x652
FAIL    github.com/openshift/odo/pkg/url        0.052s
ok      github.com/openshift/odo/pkg/url/labels (cached)
ok      github.com/openshift/odo/pkg/util       (cached)
?       github.com/openshift/odo/pkg/version    [no test files]
ok      github.com/openshift/odo/pkg/watch      (cached)
FAIL
make: *** [Makefile:144: test] Error 1

```

Just an FYI. I have no idea what happened. But looks to have caused an issue.

**Comment by johnmcollier** [comment]
@cdrage FYI I've seen this before when that unit test is run with experimental mode enabled (see https://github.com/openshift/odo/issues/2816 and https://github.com/openshift/odo/issues/2816)

**Comment by kadel** [comment]
It looks like this got resolved. Or at least I'm not able to reproduce this anymore.
@cdrage can you verify?

**Comment by cdrage** [comment]
Yup! Resolved. Closing :)
