### ISSUE TITLE
flag --delay 0 in watch command panic out

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3439]
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
```
$ odo project create test123

$ oc --request-timeout 5m import-image nodejs --namespace=test123 --from=registry.access.redhat.com/rhscl/nodejs-10-rhel7:latest --confirm

$ oc annotate istag/nodejs:latest --namespace=test123 tags=builder --overwrite

$ odo create nodejs nodejs-app --project test123 --context tests/examples/source/nodejs/

$ odo push --context tests/examples/source/nodejs/

go to another terminal and run the watch command along with flag --delay 0

$ odo watch nodejs-app --context tests/examples/source/nodejs/ --delay 0
panic: non-positive interval for NewTicker

goroutine 1 [running]:
time.NewTicker(0x0, 0xc0006d4b40)
        /usr/local/Cellar/go/1.13.7/libexec/src/time/tick.go:23 +0x147
github.com/openshift/odo/pkg/watch.WatchAndPush(0xc000238f00, 0x2b3d5c0, 0xc0000d4008, 0xc0005f1c70, 0xa, 0xc0005f1c30, 0x3, 0xc0006d4b40, 0x48, 0xc0007bee60, ...)
        /Users/amit/go/src/github.com/openshift/odo/pkg/watch/watch.go:285 +0x48a
github.com/openshift/odo/pkg/odo/cli/component.(*WatchOptions).Run(0xc000182380, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/component/watch.go:235 +0x22f
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2b71080, 0xc000182380, 0xc000496500, 0xc0003941e0, 0x1, 0x5)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/component.NewCmdWatch.func1(0xc000496500, 0xc0003941e0, 0x1, 0x5)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/component/watch.go:276 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000496500, 0xc000394190, 0x5, 0x5, 0xc000496500, 0xc000394190)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00044a500, 0x296ab78, 0xc0000b3980, 0x6)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
        /Users/amit/go/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x32a
```

## Actual behavior
panic out

## Expected behavior
As per the UX it says with delay 0 should work with performance issue but it does not panic out.  
```
--delay int        Time in seconds between a detection of code change and push.delay=0 means changes will be pushed as soon as they are detected which can cause performance issues (default 1)
``

## Any logs, error output, etc?

**Comment by mik-dass** [comment]
This is caused because time.NewTicker() needs a positive integer instead of 0. @kadel Should we remove it from the help UI or find a workaround  like a for loop?

**Comment by kadel** [comment]
> This is caused because time.NewTicker() needs a positive integer instead of 0. @kadel Should we remove it from the help UI or find a workaround like a for loop?

setting it to 0 is a perfectly valid option.
If needed we can just add special case for `0` in the code.
