### ISSUE TITLE
odo should validate postStart events before using them

### ISSUE THREAD

**Issue by maysunfaisal** [openshift/odo#3632]
/kind bug

## What versions of software are you using?

**Operating System:** Mac

**Output of `odo version`:** master

## How did you run odo exactly?
odo push 

## Actual behavior
odo panicked when i put an invalid command in the postStart event:

```
Maysuns-MacBook-Pro:nodejs-ex maysun$ odo push --show-log

Validation
 ✓  Validating the devfile [77069ns]

Creating Kubernetes resources for component madridnode
 ✓  Waiting for component to start [6s]

Applying URL changes
 ✓  URL madridnode: http://madridnode.apps.maysun2.os.fyre.ibm.com created

Syncing to component madridnode
 ✓  Checking files for pushing [1ms]
 ✓  Syncing files to the component [3s]

Executing postStart event commands for component madridnode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x22aacf6]

goroutine 1 [running]:
github.com/openshift/odo/pkg/devfile/adapters/kubernetes/component.Adapter.execDevfileEvent(0x2b720e0, 0xc0000c4000, 0x2b3e100, 0xc00050d270, 0xc000c06000, 0xc0003960f0, 0x3, 0xc000c05ab0, 0x2aef920, 0xc0005aee18, ...)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/devfile/adapters/kubernetes/component/adapter.go:505 +0x416
github.com/openshift/odo/pkg/devfile/adapters/kubernetes/component.Adapter.Push(0x2b720e0, 0xc0000c4000, 0x2b3e100, 0xc00050d270, 0xc000c06000, 0xc0003960f0, 0x3, 0xc000c05ab0, 0x2aef920, 0xc0005aee18, ...)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/devfile/adapters/kubernetes/component/adapter.go:168 +0xbe1
github.com/openshift/odo/pkg/devfile/adapters/kubernetes.Adapter.Push(0x2b46da0, 0xc0009194a0, 0xc0007fade0, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/devfile/adapters/kubernetes/adapter.go:34 +0x6c
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).devfilePushInner(0xc0007d4800, 0x0, 0x0)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/odo/cli/component/devfile.go:122 +0x4ee
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).DevfilePush(0xc0007d4800, 0xc, 0x1)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/odo/cli/component/devfile.go:39 +0x2f
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run(0xc0007d4800, 0x0, 0x0)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:213 +0x40
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2b213c0, 0xc0007d4800, 0xc00002e280, 0xc0002ba310, 0x0, 0x1)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1(0xc00002e280, 0xc0002ba310, 0x0, 0x1)
	/Users/maysun/go/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:244 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc00002e280, 0xc0002ba300, 0x1, 0x1, 0xc00002e280, 0xc0002ba300)
	/Users/maysun/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x29d
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000404f00, 0x2914e18, 0xc000045ce0, 0x2)
	/Users/maysun/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/maysun/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/Users/maysun/go/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x32a
```

## Expected behavior
it should err out if a postStart event is not a valid command

/area devfile
/assign

**Comment by maysunfaisal** [comment]
I can work on this with my preStop issue #3566
