### ISSUE TITLE
ALPHA: unable to list components from default devfile registry

### ISSUE THREAD

**Issue by kadel** [openshift/odo#3747]
using odo alpha1
```
▶ odo version
odo v2.0.0-alpha (8b213dc09)
```

Trying to run odo as a first time user. So I deleted `~/.odo`
```
▶ rm -r ~/.odo
```

Now when I try to list components from registry I get an error as no registry is configured.
If there is no registry configured in `preference.yaml` odo should automatically use our public default registry `github.com/odo-devfiles/registry`

```
▶ odo catalog list components
 ⚠  Please run 'odo registry add <registry name> <registry URL>' to add registry for listing devfile components

```

/kind bug
/area registry
/priority high

**Comment by johnmcollier** [comment]
Similar to this, when there's no preferences file, `odo registry list` panics:
```
Johns-MacBook-Pro-3:odo johncollier$ odov2 registry list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x241688a]

goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/cli/registry.(*ListOptions).Run(0x3c43808, 0x0, 0x0)
	/home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/registry/list.go:58 +0x5a
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2bbb080, 0x3c43808, 0xc00065c780, 0x3c43808, 0x0, 0x0)
	/home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/registry.NewCmdList.func1(0xc00065c780, 0x3c43808, 0x0, 0x0)
	/home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/pkg/odo/cli/registry/list.go:92 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc00065c780, 0x3c43808, 0x0, 0x0, 0xc00065c780, 0x3c43808)
	/home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000172280, 0x29ac5b0, 0xc00015c480, 0x2)
	/home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/home/wikus/syncthing/files/dev/go/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x330
```

**Comment by johnmcollier** [comment]
The commit here: https://github.com/johnmcollier/odo/commit/274acb72db1fb3ac4ec06104dae639856d6602f2 fixes things for me

Believe @cdrage was gonna pull it into his PR https://github.com/openshift/odo/pull/3705

**Comment by kadel** [comment]
fixed in alpha-2 release
/close
