### ISSUE TITLE
odo debug serial tests script panic out

### ISSUE THREAD

**Issue by amitkrout** [openshift/odo#3897]
/kind bug

## What versions of software are you using?

**Operating System:**
macOS
**Output of `odo version`:**
2.0 alpha branch
## How did you run odo exactly?
$ ginkgo $(GINKGO_FLAGS_SERIAL) -focus="odo debug command serial tests" tests/integration/debug/

## Actual behavior
panic out
```
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

        defer GinkgoRecover()

at the top of the goroutine that caused this panic.


goroutine 55 [running]:
github.com/onsi/ginkgo.Fail(0xc0000e4280, 0x78, 0xc000438128, 0x1, 0x1)
        /Users/amit/go/pkg/mod/github.com/onsi/ginkgo@v1.14.0/ginkgo_dsl.go:260 +0xc8
github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc0002e2300, 0x1cf1c00, 0x24c79a0, 0x1, 0x0, 0x0, 0x0, 0xc0002e2300)
        /Users/amit/go/pkg/mod/github.com/onsi/gomega@v1.10.1/internal/assertion/assertion.go:79 +0x20e
github.com/onsi/gomega/internal/assertion.(*Assertion).Should(0xc0002e2300, 0x1cf1c00, 0x24c79a0, 0x0, 0x0, 0x0, 0x1c03b68)
        /Users/amit/go/pkg/mod/github.com/onsi/gomega@v1.10.1/internal/assertion/assertion.go:28 +0xc7
github.com/openshift/odo/tests/integration/debug.glob..func1.3.2(0xc0002ea5a0, 0xc0002ea540)
        /Users/amit/go/src/github.com/openshift/odo/tests/integration/debug/cmd_debug_test.go:66 +0x131
created by github.com/openshift/odo/tests/integration/debug.glob..func1.3
        /Users/amit/go/src/github.com/openshift/odo/tests/integration/debug/cmd_debug_test.go:62 +0x308
```

## Expected behavior
Should not panic out

**Comment by amitkrout** [comment]
$ go version
go version go1.13.7 darwin/amd64

**Comment by amitkrout** [comment]
Unable to reproduce it on [beta-1](https://github.com/openshift/odo/releases/tag/v2.0.0-beta-1) bits
/close
