### ISSUE TITLE
odo list fails with SISSEGV when application has no odo managed components

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4183]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** 2.0.0

## How did you run odo exactly?

It seems in some cases (or always?) when odo can detect application name from non odo managed components it fails with SISSEGV  because it does not expect array of components for app to be empty. (Just my guess) .

Original issue https://github.com/redhat-developer/vscode-openshift-tools/issues/1824.

## Actual behavior

Command failed: "/home/denis/p/vscode-openshift-tools/out/tools/linux/odo" list --app app2 --project p1 -o json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x166add2]

```
goroutine 1 [running]:
github.com/openshift/odo/pkg/component.getRemoteComponentMetadata(0xc0004729a0, 0xc00073dc20, 0xa, 0x7ffe88816183, 0x4, 0x7ffe88816192, 0x2, 0x101, 0x0, 0x0, ...)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:1414 +0xd2
github.com/openshift/odo/pkg/component.GetComponent(...)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:1403
github.com/openshift/odo/pkg/component.List(0xc0004729a0, 0x7ffe88816183, 0x4, 0xc000039420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:882 +0x90a
github.com/openshift/odo/pkg/odo/cli/component.(*ListOptions).Run(0xc000753320, 0x0, 0x0)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/list.go:273 +0x15e8
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2227fc0, 0xc000753320, 0xc0008e4500, 0xc0000af380, 0x0, 0x6)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/component.NewCmdList.func1(0xc0008e4500, 0xc0000af380, 0x0, 0x6)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/list.go:338 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0008e4500, 0xc0000af320, 0x6, 0x6, 0xc0008e4500, 0xc0000af320)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000139680, 0x1fd50c8, 0xc0004cc780, 0x7)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x330
```

## Expected behavior

Returning empty array of components.

**Comment by girishramnani** [comment]
I would like to work on this

**Comment by girishramnani** [comment]
currently trying to reproduce this on a 3.11 cluster.

**Comment by girishramnani** [comment]
opened a PR to resolve it but need verification if its resolving this panic @dgolovin @mohitsuman

**Comment by mohitsuman** [comment]
@dgolovin can you please have a look.
