### ISSUE TITLE
Build error when trying to build a node.js native addon 

### ISSUE THREAD

**Issue by helio-frota** [openshift/odo#4365]
## What versions of software are you using?

**Operating System:**
Ubuntu 20.04
**Output of `odo version`:**
odo v2.0.3 (9ae754023)
## How did you run odo exactly?
odo push

## Actual behavior
```console
$ odo push

Validation
 ✓  Validating the devfile [44964ns]

Creating Kubernetes resources for component native-addon-odo
 ✓  Waiting for component to start [2ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component native-addon-odo
 ✓  Checking file changes for pushing [247844ns]
 ✓  Syncing files to the component [241ms]

Executing devfile commands for component native-addon-odo
 ✗  Executing install command "npm install" [1s]
 ✗  Failed to start component with name native-addon-odo. Error: Failed to create the component: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c cd /project && npm install]: 

> node-rdkafka@2.10.1 install /project/node_modules/node-rdkafka
> node-gyp rebuild

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 4.18.0-193.29.1.el8_2.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /project/node_modules/node-rdkafka
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN odo-nodejs-native-addon@0.0.1 No description
npm WARN odo-nodejs-native-addon@0.0.1 No repository field.
npm WARN odo-nodejs-native-addon@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2021-01-15T12_21_39_294Z-debug.log
: error while streaming command: command terminated with exit code 1
```

## Expected behavior
To build the native addons for node.js

## Any logs, error output, etc?
Logs above :+1: 

Example used: https://github.com/helio-frota/odo-nodejs-native-addon

**Comment by kadel** [comment]
This looks like "a problem" with the image used in the devfile.yaml for building the application.

The image in Devfile needs to have Python installed, the one that is currently used in https://github.com/helio-frota/odo-nodejs-native-addon/blob/0f9ea367785206e635b2aad5392bd5da3b852d9b/devfile.yaml#L15 doesn't have that.

**Comment by helio-frota** [comment]
Ok, I understand a bit the situation. Just created this issue to have some opinion/response on that. thanks.
I'm going to close this issue because this is not an odo bug.
